// Do not edit. This file is machine generated by the Resource DLL Wizard.

library PApp1;

{ITE} {DFMFileType} {UAdmin.dfm}
{ITE} {DFMFileType} {ULogon.dfm}
{ITE} {DFMFileType} {UMain.dfm}
{ITE} {DFMFileType} {UManager.dfm}
{ITE} {DFMFileType} {UPassChange.dfm}
{ITE} {DFMFileType} {UPrint.dfm}
{ITE} {DFMFileType} {UTraining.dfm}
{ITE} {DFMFileType} {UUser.dfm}
{ITE} {DFMFileType} {vcl\DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl\DBPWDLG.dfm}
{ITE} {RCFileType} {Win32\Debug\PApp1_DRC.rc}

{$R 'UAdmin.dfm' frmAdmin:TForm}
{$R 'ULogon.dfm' frmLogon:TForm}
{$R 'UMain.dfm' frmMain:TForm}
{$R 'UManager.dfm' frmManager:TForm}
{$R 'UPassChange.dfm' frmChangePassword:TForm}
{$R 'UPrint.dfm' frmPrint:TForm}
{$R 'UTraining.dfm' frmTraining:TForm}
{$R 'UUser.dfm' frmUser:TForm}
{$R 'vcl\DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl\DBPWDLG.dfm' PasswordDialog:TForm(Form)}
{$R 'Win32\Debug\PApp1_DRC.res' 'Win32\Debug\PApp1_DRC.rc'}

{$E ENG}

begin
end.
